export type DemoPlace =
  | "jurong west"
  | "tampines"
  | "bedok"
  | "woodlands"
  | "punggol"
  | "clementi"
  | "geylang"
  | "yishun"
  | "pasir ris"
  | "sembawang"
  | "bukit batok"
  | "queenstown"
  | "toa payoh"
  | "hougang"
  | "ang mo kio"
  | "bishan"
  | "marine parade"
  | "serangoon"
  | "orchard"
  | "changi"
  | "online";

export type DemoRow = {
  brand: string;
  registered: string;
  tags: string[];
  place: DemoPlace;
  summary: string;
  description: string;
  urls: { url: string; label: string }[];
  verification: "uen_document" | "linkedin";
};

export const DEMO_OWNERS = [
  { id: "demo-owner-east", displayName: "Aisyah Rahman", slug: "aisyah-rahman-demo" },
  { id: "demo-owner-west", displayName: "Hafiz Abdullah", slug: "hafiz-abdullah-demo" },
  { id: "demo-owner-central", displayName: "Nurul Iman", slug: "nurul-iman-demo" },
] as const;

export const EXTRA_TAGS: { name: string; parent: string }[] = [
  { name: "Plumbing", parent: "services" },
  { name: "Electrical", parent: "services" },
  { name: "Cleaning", parent: "services" },
  { name: "Moving", parent: "services" },
  { name: "Printing", parent: "services" },
  { name: "IT", parent: "services" },
  { name: "Florist", parent: "services" },
  { name: "Grocery", parent: "retail" },
  { name: "Fashion", parent: "retail" },
  { name: "Books", parent: "retail" },
  { name: "Tuition", parent: "education" },
  { name: "Quran", parent: "education" },
  { name: "Clinic", parent: "health" },
  { name: "Dental", parent: "health" },
  { name: "Legal", parent: "professional" },
  { name: "Accounting", parent: "professional" },
  { name: "Insurance", parent: "professional" },
];

export const DEMO_BUSINESSES: DemoRow[] = [
  {
    brand: "Saffron Kenduri Kitchen",
    registered: "Saffron Kenduri Kitchen Pte. Ltd.",
    tags: ["catering", "food"],
    place: "jurong west",
    summary: "Kenduri trays and buffet packs from a Jurong West kitchen.",
    description:
      "## What we cook\n\nNasi ambeng, briyani, and vegetable trays for twelve to two hundred people.\n\n- Weekday office iftars\n- Home kenduri\n- School events\n\nCall with a date and headcount. This is sample data.",
    urls: [{ url: "https://example.com/saffron-kenduri", label: "Website" }],
    verification: "uen_document",
  },
  {
    brand: "Nur Hall Tampines",
    registered: "Nur Spaces LLP",
    tags: ["hall", "venue"],
    place: "tampines",
    summary: "A family hall in Tampines for birthdays and small majlis.",
    description: "Air-conditioned hall for up to 80 people. Tables and chairs included. Sample listing only.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Bedok Loaf",
    registered: "Bedok Loaf Bakery Pte. Ltd.",
    tags: ["bakery", "food"],
    place: "bedok",
    summary: "Buns, tarts, and birthday cakes from Bedok.",
    description: "",
    urls: [{ url: "https://example.com/bedok-loaf", label: "Orders" }],
    verification: "linkedin",
  },
  {
    brand: "Padang Geylang House",
    registered: "Padang Geylang House Pte. Ltd.",
    tags: ["restaurant", "food"],
    place: "geylang",
    summary: "Nasi padang plates and family trays near Geylang Serai.",
    description: "## Menu notes\n\nRendang, sambal goreng, and sayur lodeh. Demo kitchen, not a real shop.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Kampong Glam Kopi",
    registered: "Kampong Glam Kopi",
    tags: ["hawker", "food"],
    place: "orchard",
    summary: "",
    description: "A sample hawker stall listing for kopi and toast.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Studio Cahaya",
    registered: "Cahaya Pictures Pte. Ltd.",
    tags: ["photography", "party-logistics"],
    place: "punggol",
    summary: "Family portraits and kenduri coverage.",
    description: "Two-hour home sessions or hall coverage. Sample photographer.",
    urls: [
      { url: "https://example.com/studio-cahaya", label: "Portfolio" },
      { url: "https://www.linkedin.com/company/studio-cahaya-demo", label: "LinkedIn" },
    ],
    verification: "linkedin",
  },
  {
    brand: "Balloon & Bunting Co",
    registered: "Balloon And Bunting Co Pte. Ltd.",
    tags: ["decor", "party-logistics"],
    place: "hougang",
    summary: "Balloon garlands and simple backdrop hire.",
    description: "",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Folding Table Rentals",
    registered: "Folding Table Rentals",
    tags: ["rental", "party-logistics"],
    place: "woodlands",
    summary: "Tables, chairs, and coolers for home gatherings in the north.",
    description: "Weekend delivery to Woodlands and Yishun. Demo inventory.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Tampines Prints Demo",
    registered: "Tampines Prints Demo Pte. Ltd.",
    tags: ["printing", "services"],
    place: "tampines",
    summary: "Invitations, banners, and name cards.",
    description: "## Print list\n\n- A3 posters\n- Door gifts tags\n- Simple invites\n",
    urls: [{ url: "https://example.com/tampines-prints", label: "Website" }],
    verification: "uen_document",
  },
  {
    brand: "East Coast Pipeworks",
    registered: "East Coast Pipeworks Pte. Ltd.",
    tags: ["plumbing", "services"],
    place: "bedok",
    summary: "A plumber for leaks and tap changes in the east.",
    description: "Sample trades listing for search tests such as plumber in Tampines or Bedok.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Switchfix Electrical",
    registered: "Switchfix Electrical Pte. Ltd.",
    tags: ["electrical", "services"],
    place: "clementi",
    summary: "Light fittings and socket work in the west.",
    description: "",
    urls: [{ url: "https://example.com/switchfix", label: "Contact form" }],
    verification: "linkedin",
  },
  {
    brand: "Harmoni Cleaners",
    registered: "Harmoni Cleaners LLP",
    tags: ["cleaning", "services"],
    place: "toa payoh",
    summary: "Home and hall cleaning after a gathering.",
    description: "Two-person team, four-hour slots. Demo only.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Pindah Movers",
    registered: "Pindah Movers Pte. Ltd.",
    tags: ["moving", "services"],
    place: "yishun",
    summary: "A van and two movers for HDB shifts.",
    description: "",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Ayat Tuition",
    registered: "Ayat Tuition",
    tags: ["tuition", "education"],
    place: "bishan",
    summary: "Primary maths and science in small groups.",
    description: "Sample tuition centre. Not a real MOE centre.",
    urls: [{ url: "https://example.com/ayat-tuition", label: "Timetable" }],
    verification: "uen_document",
  },
  {
    brand: "Nur Clinic Bedok",
    registered: "Nur Clinic Bedok Pte. Ltd.",
    tags: ["clinic", "health"],
    place: "bedok",
    summary: "A GP clinic listing for directory tests.",
    description: "## Hours\n\nWeekday evenings. This is not a real clinic and must not be used for care.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Ameen Dental",
    registered: "Ameen Dental Pte. Ltd.",
    tags: ["dental", "health"],
    place: "serangoon",
    summary: "Family dentistry sample listing in Serangoon.",
    description: "",
    urls: [{ url: "https://example.com/ameen-dental", label: "Website" }],
    verification: "linkedin",
  },
  {
    brand: "Kitab Corner",
    registered: "Kitab Corner Books",
    tags: ["books", "retail"],
    place: "geylang",
    summary: "Malay and English books, including children’s titles.",
    description: "A sample bookshop near Geylang Serai.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Modest Thread",
    registered: "Modest Thread Pte. Ltd.",
    tags: ["fashion", "retail"],
    place: "orchard",
    summary: "Ready-to-wear kebaya and everyday modest wear.",
    description: "",
    urls: [{ url: "https://example.com/modest-thread", label: "Shop" }],
    verification: "uen_document",
  },
  {
    brand: "Pasar Mini Hougang",
    registered: "Pasar Mini Hougang",
    tags: ["grocery", "retail"],
    place: "hougang",
    summary: "Dry goods, spices, and frozen packs.",
    description: "Neighbourhood mini-mart sample. Opening hours are invented.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Adil Accounting",
    registered: "Adil Accounting PAC",
    tags: ["accounting", "professional"],
    place: "online",
    summary: "Bookkeeping for small private limited companies.",
    description: "Online-only sample professional listing. No map pin.",
    urls: [{ url: "https://example.com/adil-accounting", label: "Website" }],
    verification: "linkedin",
  },
  {
    brand: "Hakam Legal Desk",
    registered: "Hakam Legal Desk LLC",
    tags: ["legal", "professional"],
    place: "online",
    summary: "Wills and simple company paperwork, sample copy only.",
    description: "Not a law practice. Demo text for professional search.",
    urls: [],
    verification: "linkedin",
  },
  {
    brand: "Takaful Notes",
    registered: "Takaful Notes Pte. Ltd.",
    tags: ["insurance", "professional"],
    place: "online",
    summary: "A sample insurance advisory listing.",
    description: "",
    urls: [{ url: "https://example.com/takaful-notes", label: "About" }],
    verification: "uen_document",
  },
  {
    brand: "Quran Circle Yishun",
    registered: "Quran Circle Yishun",
    tags: ["quran", "education"],
    place: "yishun",
    summary: "Weekend tajwid class for children.",
    description: "Sample education listing. Not affiliated with any mosque.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Fitrah Movement Studio",
    registered: "Fitrah Movement Studio Pte. Ltd.",
    tags: ["studio", "venue"],
    place: "queenstown",
    summary: "A small studio for classes and photoshoots.",
    description: "Hourly hire. Demo venue.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Marine Parade Blooms",
    registered: "Marine Parade Blooms",
    tags: ["florist", "services"],
    place: "marine parade",
    summary: "Bouquets and simple pelamin flowers.",
    description: "",
    urls: [{ url: "https://example.com/mp-blooms", label: "Catalogue" }],
    verification: "uen_document",
  },
  {
    brand: "Woodlands IT Fix",
    registered: "Woodlands IT Fix Pte. Ltd.",
    tags: ["it", "services"],
    place: "woodlands",
    summary: "Laptop repair and Wi-Fi setup at home.",
    description: "Sample IT service for the north.",
    urls: [],
    verification: "linkedin",
  },
  {
    brand: "Clementi Cycle Care",
    registered: "Clementi Cycle Care",
    tags: ["services"],
    place: "clementi",
    summary: "Bicycle servicing near Clementi.",
    description: "",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Bishan Party Cake",
    registered: "Bishan Party Cake Pte. Ltd.",
    tags: ["bakery", "food"],
    place: "bishan",
    summary: "Buttercream cakes for twelve to forty slices.",
    description: "## Flavours\n\nPandan, chocolate, and red velvet. Demo bakery.",
    urls: [{ url: "https://example.com/bishan-cake", label: "Orders" }],
    verification: "uen_document",
  },
  {
    brand: "Toa Payoh Soto Stall",
    registered: "Toa Payoh Soto Stall",
    tags: ["hawker", "food"],
    place: "toa payoh",
    summary: "Mee soto and satay from a sample hawker listing.",
    description: "",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Queenstown Henna",
    registered: "Queenstown Henna",
    tags: ["services"],
    place: "queenstown",
    summary: "Bridal and party henna, sample artist.",
    description: "Home visits in the central area.",
    urls: [{ url: "https://example.com/qt-henna", label: "Instagram stand-in" }],
    verification: "uen_document",
  },
  {
    brand: "Sembawang Frozen Cuts",
    registered: "Sembawang Frozen Cuts Pte. Ltd.",
    tags: ["grocery", "retail"],
    place: "sembawang",
    summary: "Frozen poultry and marinades for home cooks.",
    description: "",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Punggol Family Hall",
    registered: "Punggol Family Hall Pte. Ltd.",
    tags: ["hall", "venue"],
    place: "punggol",
    summary: "Ground-floor hall for birthday lunch.",
    description: "Capacity 60. Sample pin in Punggol.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Ang Mo Kio Study Hub",
    registered: "Ang Mo Kio Study Hub",
    tags: ["tuition", "education"],
    place: "ang mo kio",
    summary: "Secondary English and Malay tuition.",
    description: "",
    urls: [{ url: "https://example.com/amk-study", label: "Website" }],
    verification: "linkedin",
  },
  {
    brand: "Pasir Ris Party Pool",
    registered: "Pasir Ris Party Pool Pte. Ltd.",
    tags: ["rental", "venue"],
    place: "pasir ris",
    summary: "Private pool slots for small birthday groups.",
    description: "Weekend mornings only. Demo venue, not a real condo booking.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Bukit Batok Paintworks",
    registered: "Bukit Batok Paintworks Pte. Ltd.",
    tags: ["services"],
    place: "bukit batok",
    summary: "Room painting and touch-ups.",
    description: "Useful for search phrases about renovate or paint.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Rukyah Books Online",
    registered: "Rukyah Books Online",
    tags: ["books", "retail"],
    place: "online",
    summary: "Ships children’s books across Singapore.",
    description: "Online-only sample shop. No map pin.",
    urls: [{ url: "https://example.com/rukyah-books", label: "Shop" }],
    verification: "uen_document",
  },
  {
    brand: "Cloud Payroll Demo",
    registered: "Cloud Payroll Demo Pte. Ltd.",
    tags: ["accounting", "professional", "it"],
    place: "online",
    summary: "Payroll software for small teams, sample listing.",
    description: "",
    urls: [{ url: "https://example.com/cloud-payroll-demo", label: "Product" }],
    verification: "linkedin",
  },
  {
    brand: "Serangoon Nasi Ambeng",
    registered: "Serangoon Nasi Ambeng Pte. Ltd.",
    tags: ["catering", "food"],
    place: "serangoon",
    summary: "Ambeng trays for ten, twenty, or forty.",
    description: "## How to order\n\nTwo days’ notice. Demo kitchen.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Joo Chiat Kuih Cart",
    registered: "Joo Chiat Kuih Cart",
    tags: ["bakery", "hawker", "food"],
    place: "marine parade",
    summary: "Kuih lapis, ondeh-ondeh, and bingka.",
    description: "",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Changi Village Grill",
    registered: "Changi Village Grill Pte. Ltd.",
    tags: ["restaurant", "food"],
    place: "changi",
    summary: "Grilled fish and family set meals near Changi Village.",
    description: "A sample restaurant pin for east-side search.",
    urls: [{ url: "https://example.com/changi-grill", label: "Menu" }],
    verification: "uen_document",
  },
  {
    brand: "Pioneer Hawker Group",
    registered: "Pioneer Hawker Group Pte. Ltd.",
    tags: ["hawker", "food"],
    place: "jurong west",
    summary: "Operates two sample stalls in the west.",
    description: "",
    urls: [],
    verification: "linkedin",
  },
  {
    brand: "Little Mihrab Preschool",
    registered: "Little Mihrab Preschool Pte. Ltd.",
    tags: ["education"],
    place: "pasir ris",
    summary: "A preschool listing for directory layout tests.",
    description: "Not a licensed centre. Sample copy only.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Healing Hands Physio",
    registered: "Healing Hands Physio Pte. Ltd.",
    tags: ["clinic", "health"],
    place: "bukit batok",
    summary: "Sports physio sample listing.",
    description: "Do not book care from this page. Demo data.",
    urls: [{ url: "https://example.com/hh-physio", label: "Website" }],
    verification: "uen_document",
  },
  {
    brand: "Frame and Flash Video",
    registered: "Frame And Flash Video Pte. Ltd.",
    tags: ["photography", "party-logistics"],
    place: "ang mo kio",
    summary: "Highlight videos for birthdays and kenduri.",
    description: "",
    urls: [],
    verification: "linkedin",
  },
  {
    brand: "Gold Ribbon Events",
    registered: "Gold Ribbon Events Pte. Ltd.",
    tags: ["decor", "rental", "party-logistics"],
    place: "sembawang",
    summary: "Backdrop, draping, and chair covers.",
    description: "## Packages\n\n- Birthday\n- Pelamin simple\n- Corporate iftar\n",
    urls: [{ url: "https://example.com/gold-ribbon", label: "Lookbook" }],
    verification: "uen_document",
  },
  {
    brand: "Van and Driver SG",
    registered: "Van And Driver SG",
    tags: ["moving", "services"],
    place: "hougang",
    summary: "A driver with a van for errands and small moves.",
    description: "",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Circuit Breaker Electric",
    registered: "Circuit Breaker Electric Pte. Ltd.",
    tags: ["electrical", "services"],
    place: "punggol",
    summary: "Consumer unit checks and lighting.",
    description: "Sample electrician for repair searches.",
    urls: [],
    verification: "uen_document",
  },
  {
    brand: "Quiet Office Studio",
    registered: "Quiet Office Studio Pte. Ltd.",
    tags: ["studio", "venue", "professional"],
    place: "orchard",
    summary: "Hot-desk studio for photos and meetings.",
    description: "",
    urls: [{ url: "https://example.com/quiet-office", label: "Book" }],
    verification: "linkedin",
  },
  {
    brand: "Kampung Grocery Box",
    registered: "Kampung Grocery Box Pte. Ltd.",
    tags: ["grocery", "retail"],
    place: "online",
    summary: "Weekly spice and dry-goods box, ships islandwide.",
    description: "Online-only sample grocer.",
    urls: [{ url: "https://example.com/kampung-box", label: "Subscribe" }],
    verification: "uen_document",
  },
  {
    brand: "Waqf Will Advisors",
    registered: "Waqf Will Advisors LLC",
    tags: ["legal", "professional"],
    place: "online",
    summary: "Sample will-writing advisory. Not legal advice.",
    description: "Use this listing to test professional and online filters.",
    urls: [],
    verification: "linkedin",
  },
];
